baseURL: 'https://www.svorstol.com'
languageCode: en-US
theme: hugo-bearcub
title: Stein-Otto Svorstøl

parmas.author:
  name: Stein-Otto Svorstøl
  email: stein-otto@svorstol.com

params:
  goatcounterID: svorstol

ignoreLogs: ['warning-goldmark-raw-html']
